_target_: torch.utils.data.DataLoader
dataset: 
  _target_: dataset.CelebAHQDataset
  name: celebahq
  split: train
  path_data: data/datasets/celebahq
  path_labels: data/metadata/celebahq/labels.csv
  path_predictions: data/metadata/celebahq/predictions/train/classifiers.DenseNet/data.csv
  n_samples: ${exp.n_samples}
  label_id: ${exp.label_id}
  n_skip: 0
batch_size: ${exp.n_unique} # to change if n_unique is larger
num_workers: 0