defaults:
  - _self_
  - noise_tunnel: default

_partial_: true
_target_: explainers.FreeFormMask

method:
  _partial_: true
  _target_: captum.attr.IntegratedGradients

path: ???
# mask_size: "20-30% freeform"
mask_size: "10-20% freeform"
mask_idx: 0
use_random: false
iterate: false

# those are ignored
area: 0.3
cell_size: 16
binarize: true
cell_strided: false
quantile: null
scale: false
smoothing: false
ignore_over_quantile: null

get_attr_maps_kwargs:
  internal_batch_size: 64
  
sign: absolute_value