defaults:
  - _self_
  - noise_tunnel: default

_partial_: true
_target_: explainers.IntegratedGradients

method:
  _partial_: true
  _target_: captum.attr.IntegratedGradients

area: 0.3
cell_size: 16
binarize: true
cell_strided: false
quantile: null
scale: false
smoothing: false
ignore_over_quantile: null

get_attr_maps_kwargs:
  internal_batch_size: 64
  
sign: absolute_value