defaults:
  - _self_
  - noise_tunnel: default

_partial_: true
_target_: explainers.LIME

method:
  _partial_: true
  _target_: captum.attr.Lime

area: 0.3
cell_size: 16
binarize: true
cell_strided: false
quantile: null
scale: false
smoothing: false
ignore_over_quantile: null

get_attr_maps_kwargs:
  n_samples: 128
  feature_mask:
    _partial_: true
    _target_: explainers.utils.get_superpixels
    quickshift_kwargs:
      rng:  ${exp.seed}

sign: absolute_value